server:
  port: 9090
spring:
  application:
    name: InventoryService
  datasource:
    url: jdbc:mysql://localhost:3306/inventory_db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

axon:
  eventhandling:
    processors:
      product-group:
        mode: subscribing
  axonserver:
    client-id: InventoryService
  serializer:
    general: default
    events: jackson
    messages: jackson
