name: car-demo-common-service

on:
  push:
    branches: [ main ]
env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK! ${{ github.workspace }}"
        env:
          First_Name: Mona AA
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: maven
      - name: SonarCloud Scan
        run: mvn verify sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=nashtech
        working-directory: ${{ github.workspace }}
        env:
         # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  setup-build-publish-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }}
      - uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GKE_KEY }}
      - uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.GKE_PROJECT }}

        # Configure Docker to use the gcloud command-line tool as a credential 
        # helper for authentication
      - name: configure docker
        run: |-
          gcloud --quiet auth configure-docker

      - name: Build, Publish, and Deploy
        run: |
          . apps-deployment-script.sh "us-east1"
        env:
         GITHUB_TOKEN: ${{ github.token }}
